### ISSUE TITLE
Implement endpoints to help Conduit

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-federation-api#2]
From @timokoesters:
My wishlist for ruma-federation-api endpoints:

    GET make_join
    PUT send_join
    GET query/directory
    PUT send

**Comment by iinuwa** [comment]
@timokoesters, the `make_join`, `send_join` and `query/directory` endpoints are all in `master`. Let me know if you have any issues.

**Comment by iinuwa** [comment]
PUT /send still has an open PR (didn't clarify that above)

**Comment by jplatte** [comment]
Oh, right. Let's just say the remaining work is being tracked in #8 then :)
