### ISSUE TITLE
Add help files for contributors

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-federation-api#5]
We should at least copy the CONTRIBUTING.md file from ruma-client-api, define an .editorconfig, and maybe some other files.

**Comment by iinuwa** [comment]
I added the CONTRIBUTING.md file and added a note about possibly adding `cargo fmt && cargo clippy --all-targets --all-features` to git hooks to prevent CI failures.

@jplatte do you still think we need an .editorconfig?

**Comment by jplatte** [comment]
We don't strictly need it, but I think I'll still add one to each of our repositories.

**Comment by iinuwa** [comment]
Note to self: add whitespace for struct fields convention to CONTRIBUTING.md

**Comment by jplatte** [comment]
@iinuwa If you want to have an issue for the whitespace in CONTRIBUTING.md, I think it now makes sense to open that separately on ruma/ruma and self-assign. No point in updating the CONTRIBUTING.md here if this repo is soon merged into the other one.
